name: Deploy LARP tool

on:
  push:
    branches: ["pathologic_tool"]
    paths: 
      - 'larp.tool/**'  # Триггерим деплой только при изменениях в папке

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: cd larp.tool && npm install && npm run build -- --configuration production
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www  # Путь до собранного Angular-проекта
          branch: gh-pages
