name: Deploy LARP tool

on:
  push:
    branches: ["pathologic_tool"]
    paths: 
      - 'larp.tool/**'  # Триггерим деплой только при изменениях в папке

jobs:
  deploy:
    if: "contains(github.event.head_commit.message, '[deploy]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: cd larp.tool && npm install && npm run build --configuration=production
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: larp.tool/www  # Путь до собранного Angular-проекта
          branch: gh-pages


  add-html-file:
    if: "contains(github.event.head_commit.message, '[deploy]')"
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout gh-pages
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: gh-pages
    
    - name: Create HTML file
      run: |
        cd gh-pages
        cat > 404.html << 'EOF'
        <!DOCTYPE html>
        <script>
          sessionStorage.redirect = location.href;
          location.replace('/larp/');
        </script>
        EOF
    
    - name: Commit and push
      run: |
        cd gh-pages
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add 404.html
        git commit -m "Add 404"
        git push
